object Versions {
    const val coreKtx = "1.12.0"
    const val lifecycle_runtime_ktx = "2.6.2"
    const val activity_compose = "1.8.0"
    const val compose_bom = "2023.03.00"
    const val junit = "4.13.2"
    const val androidx_junit = "1.1.5"
    const val espresso_core = "3.5.1"
    const val androidx_compose_bom = "2023.03.00"
    const val lifecycle_version = "2.6.2"
    const val appcompat = "1.6.1"
    const val hiltAndroid = "2.48.1"
    const val hiltAndroidCompiler = "2.48.1"
    const val hiltCompiler = "1.1.0-rc01"
    const val hiltNavigationCompose = "1.1.0-rc01"
    const val retrofit = "2.9.0"
    const val okhttp = "2.7.5"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.15.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.12.0"
    const val coroutinesCore = "1.7.3"
    const val coroutinesAndroid = "1.7.3"
}